# Generated by Django 3.0.7 on 2020-09-07 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pool',
            name='vote_img1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pool',
            name='vote_img2',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(max_length=30)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_vote', to='my_app.Pool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vote', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'pool', 'vote_type')},
            },
        ),
    ]
