# Generated by Django 3.0.7 on 2020-09-07 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20200907_1608'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserVote',
        ),
    ]
