# Generated by Django 3.0.7 on 2020-09-08 03:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0003_delete_uservote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='vote_img1',
        ),
        migrations.AddField(
            model_name='pool',
            name='vote_img1',
            field=models.ManyToManyField(related_name='img_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='pool',
            name='vote_img2',
        ),
        migrations.AddField(
            model_name='pool',
            name='vote_img2',
            field=models.ManyToManyField(related_name='img_2', to=settings.AUTH_USER_MODEL),
        ),
    ]
