# Generated by Django 3.0.7 on 2020-09-09 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0004_auto_20200908_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='vote_img1',
            field=models.ManyToManyField(blank=True, related_name='img_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pool',
            name='vote_img2',
            field=models.ManyToManyField(blank=True, related_name='img_2', to=settings.AUTH_USER_MODEL),
        ),
    ]
